volumes:
  mysql-data:
    driver: local

networks:
  network:
    driver: bridge

services:
  php:
    build: ./docker/php
    container_name: kwai-orders-php
    volumes:
      - .:/var/www/app
    networks:
      - "network"

  nginx:
    build: ./docker/nginx
    container_name: kwai-orders-nginx
    ports:
      - "7040:8080"
    volumes_from:
      - php
    depends_on:
      - php
    networks:
      - "network"

  mysql:
    build: ./docker/mysql
    container_name: kwai-orders-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "7041:3306"
    environment:
      - "MYSQL_DATABASE=kwai_orders"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - "network"

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    container_name: kwai-orders-redis
    volumes:
      - ./storage/framework/cache/data:/data
    ports:
      - 6379:6379
    networks:
      - network
  
  soketi:
    image: 'quay.io/soketi/soketi:1.4-16-debian'
    container_name: kwai-orders-soketi
    ports:
      - "6001:6001"
      - "9601:9601"
    environment:
      - "SOKETI_DEBUG=1"
      - "SOKETI_DB_REDIS_HOST=redis"
      - "SOKETI_DEFAULT_APP_ID=kwai-orders-id"
      - "SOKETI_DEFAULT_APP_KEY=kwai-orders-key"
      - "SOKETI_DEFAULT_APP_SECRET=kwai-orders-secret"
      - "METRICS_SERVER_PORT=9601"
    networks:
      - "network"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M
