volumes:
  mysql-data:
    driver: local

networks:
  network:
    driver: bridge

services:
  php:
    build: ./docker/php
    container_name: kwai-orders-php
    volumes:
      - .:/var/www/app
    networks:
      - "network"

  nginx:
    build: ./docker/nginx
    container_name: kwai-orders-nginx
    ports:
      - "7040:8080"
    volumes_from:
      - php
    depends_on:
      - php
    networks:
      - "network"

  mysql:
    build: ./docker/mysql
    container_name: kwai-orders-mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "7041:3306"
    environment:
      - "MYSQL_DATABASE=kwai_orders"
      - "MYSQL_ROOT_PASSWORD=root"
    networks:
      - "network"
